// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZwVuT0vwOJkWzzjBtpdfoLa2EbLfkQW0',
    appId: '1:442388366486:web:89f37f13c3f86f879feeb7',
    messagingSenderId: '442388366486',
    projectId: 'fore-coffee-app',
    authDomain: 'fore-coffee-app.firebaseapp.com',
    storageBucket: 'fore-coffee-app.firebasestorage.app',
    measurementId: 'G-5956NB0543',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzZ4Wis_ZsRmVIP0QZ0gWjfHNJXTb-mBI',
    appId: '1:442388366486:android:848c4641fd9f14949feeb7',
    messagingSenderId: '442388366486',
    projectId: 'fore-coffee-app',
    storageBucket: 'fore-coffee-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxfU1u11qaNoqgvuiyHPcpfpqDuvd-L_E',
    appId: '1:442388366486:ios:eb1b214d864445659feeb7',
    messagingSenderId: '442388366486',
    projectId: 'fore-coffee-app',
    storageBucket: 'fore-coffee-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterFore1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxfU1u11qaNoqgvuiyHPcpfpqDuvd-L_E',
    appId: '1:442388366486:ios:eb1b214d864445659feeb7',
    messagingSenderId: '442388366486',
    projectId: 'fore-coffee-app',
    storageBucket: 'fore-coffee-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterFore1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZwVuT0vwOJkWzzjBtpdfoLa2EbLfkQW0',
    appId: '1:442388366486:web:81163c07082a4dff9feeb7',
    messagingSenderId: '442388366486',
    projectId: 'fore-coffee-app',
    authDomain: 'fore-coffee-app.firebaseapp.com',
    storageBucket: 'fore-coffee-app.firebasestorage.app',
    measurementId: 'G-WTM6NDJFMM',
  );
}
